version: '3.8'

services:
  # Application
  api:
    image: thanakritssw/parkease:latest
    container_name: parkease
    ports:
      - 4000:4000
    expose:
      - 4000
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
networks:
  default:
    name: nginx
    
