version: '3.8'

services:

  # Application
  api:
    image: thanakritssw/parkease:latest
    container_name: parkease
    ports:
      - 80:4000
    expose:
      - 80
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
# volumes:
#   db_data: