version: '3.8'

services:
  api:
    image: thanakritssw/parkease:latest
    container_name: parkease
    ports:
      - 4000:4000
    expose:
      - 4000
    networks:
      - default
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - default
    
